kyverno/KDP

README.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
=> feat: store kyverno policies in OCI registries

README.md, proposals/image_verify_enhancements.md
=> migrate image verification proposal

OLD.md
=> add OLD.md

proposals/image_verify_enhancements.md
=> update digest tags

README.md, proposals/template.md
Adds an appropriate template and review process for KDPs.
Open for review/discussion around the template and voting process.
Fixes #7
=> Add KDP review/acceptance procedure + template

README.md, proposals/mutate_existing_resources.md, proposals/template.md
This PR:
- Updates the template
- Adds the link to the implementation PR
- Updates KDP status
Signed-off-by: ShutingZhao <shuting@nirmata.com>
=> Updates the template

proposals/generate_existing_resources.md
Signed-off-by: prateekpandey14 <prateek.pandey@nirmata.com>
Converted the [google docs](https://docs.google.com/document/d/1KHf19cV5o8fWWC78OBl3H1-OETRuzHciEEBTfRFfMUU/edit#heading=h.w8ahammwm4ug)  to a KDP proposal template
=> Add KDP - Generate Existing Resources

proposals/allow_time_based_window_for_policy_enforcement_behavior
Signed-off-by: Prateeknandle <prateeknandle@gmail.com>
=> Allow time-based window for policy enforcement behavior

proposals/extend_pod_security_admission.md
Signed-off-by: ShutingZhao <shuting@nirmata.com>
=> Extending Pod Security Admission

proposals/policy_report_spilt.md
Signed-off-by: prateekpandey14 <prateek.pandey@nirmata.com>
=> PolicyReport spilt up per policy

README.md, proposals/cli_schema.md
This KDP proposes a new CLI schema for the `kyverno test` command and will be the subject of an LFX mentorship the primary mentors of which are @chipzoller and @vyankyGH.
Your collaboration on this KDP is essential to reach a solidified design.
=> `kyverno test` new CLI schema proposal

proposals/extend_pod_security_admission.md
- Changed policy names and titles.
- Add an example to exclude fields outside container objects with labels.
=> Extend PSA: improvements

README.md, proposals/extend_pod_security_admission.md
=> update PSa+ and ToC

proposals/Remove deprecated CRD types and apiextensions.JSON.md
Proposes an idea for Remove deprecated CRD types and apiextensions.JSON
=> Remove deprecated CRD types and apiextensions.JSON

proposals/clone_mulitple_resource.md
Proposes an idea to extend the generate rule to clone multiple resources from a namespace.
Signed-off-by: prateekpandey14 <prateek.pandey@nirmata.com>
=> KDP for allow cloning multiple resources

proposals/cleanup.md
Signed-off-by: Nikhil Sharma <nikhilsharma230303@gmail.com>
This PR adds **Pros and Cons** of both the implementations which can be used for adding the **cleanup rule** in Kyverno to the cleanup proposal.
Sharing these points with the broader community for getting their review on this.
=> add Pros and Cons of both the implementations which can be used for adding the cleanup rule in Kyverno

README.md
Signed-off-by: Pratik Shah <pratik@infracloud.io>
=> Added cache enhancement in readme

proposals/service_api_calls.md
Initial proposal at: https://github.com/kyverno/KDP/issues/14.
=> proposal for Service API calls 

proposals/support_cel_validations.md
Adding an initial proposal for supporting CEL in Kyverno Engine
=> Proposal: CEL Validation Support in Kyverno Engine

proposals/cleanup.md
Fixed the inconsistencies, and replaced the annotations with labels and similar fixes.
Closes #44
=> [Docs]: Fix the inconsistencies in the cleanup proposal

proposals/generate_validating_admission_policies.md
Adding an initial proposal for generating validating admission policies.
=> Proposal for generating VAPs from Kyverno policies
